#!/bin/sh

# auto: automatically clear screen and run command when file changes

# auto mandoc repl.1 \| ul     (watches repl.1)
# auto wc -l repl.c \> lines   (watches repl.c)

# parse arguments

clear=0
wargs= # args for watch

args=`getopt ci $*`
[ $? -ne 0 ] && { echo "usage: $0 [-ci] command ..." 1>&2; exit 1; }
set -- $args

while [ $# -ne 0 ]; do
	case "$1" in
	-c) clear=1; shift ;;
	-i) wargs=-i; shift ;;
	--) shift; break;;
	esac
done

# locate file in argv (preceding any of sh's infix operators)

eval file=\$$#

i=
for arg in "$@"; do
	case "$arg" in
	'|'|'>'|'>>'|'<'|'&'|'&&'|'||')
		eval file=\$$i
		break
		;;
	esac
	: $((i++))
done

# run command

if [ $clear = 1 ]; then
	watch $wargs "$file" | while read; do clear && eval "$@"; done
else
	watch $wargs "$file" | while read; do eval "$@"; done
fi
