#!/bin/sh

# open man page as HTML document
# (with .html to make sure Chrome displays it correctly)

file=$(mktemp /tmp/man.XXXXXX) || exit 1
mv $file $file.html
MANPAGER=cat man -T html "$@" > $file.html
xdg-open $file.html
rm $file.html
