#!/bin/sh

err() { echo "$@" 1>&2; exit 1; }

[ $# -ne 0 ] && err "usage: $0"

[ ! -d /tmp/less$PWD ] && err "/tmp/less$PWD does not exist (have you run less-refresh?)"
mkdir -p /tmp/less$PWD

echo $$ > /tmp/less$PWD/pid
exec less /tmp/less$PWD/view
