#!/bin/ksh

# unwrap file $1/$1 to $1 and delete directory $1

if [ "$(ls "$1" | wc -l)" -ne 1 ]; then
	echo "$1 contains more than one file" 1>&2
	exit 1
fi

if [ ! -e "${1}/${1}" -a ! -d "${1}/${1}" ]; then
	echo "${1}/${1} does not exist" 1>&2
	exit 1
fi

prefix=$RANDOM
while [ -e "${prefix}.${1}" ]; do prefix=$RANDOM; done

mv "$1" "${prefix}.${1}"
mv "${prefix}.${1}/${1}" "$1"
rm -r "${prefix}.${1}"
