#!/bin/ksh

# wrap file $1 in a directory $1

prefix=$RANDOM
while [ -e "${prefix}.${1}" ]; do prefix=$RANDOM; done

mv "$1" "${prefix}.${1}"
mkdir "$1"
mv "${prefix}.${1}" "$1"
mv "${1}/${prefix}.${1}" "${1}/${1}"
