#!/bin/ksh

set -A paths -- /usr/local/share/applications ~/.local/share/applications

usage() {
	echo "usage: $0 [-f] desktop-entry" 1>&2
}
err_no_file() {
	echo "$file does not exist" 1>&2 && exit 1
}

[ $# -lt 1 -o $# -gt 2 ] && usage && exit 1

fake=false
if [ $# -eq 2 ]; then
	opt=$1
	file=$2
	case "$opt" in
		-f) fake=true ;;
		*) usage && exit 1 ;;
	esac
else
	file=$1
fi

basename=$(basename "$file")

if [[ $basename != $file ]]; then # absolute path
	[[ ! -e $file ]] && err_no_file
else # relative path
	i=0
	while [[ ! -e $file ]]; do
		[[ $i -gt ${#paths[@]} ]] && err_no_file
		file=${paths[$((i++))]}/$basename
	done
fi

mime_types=$(cat "$file" | grep ^MimeType= | sed 's/^MimeType=//')

IFS=';'
for mime_type in $mime_types; do
	echo xdg-mime default "$(basename "$file")" $mime_type
	if [ "$fake" = false ]; then
		xdg-mime default "$(basename "$file")" $mime_type
	fi
done
